//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despacho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Despacho()
        {
            this.Puesto_Despacho = new HashSet<Puesto_Despacho>();
        }
    
        public int CodDespacho { get; set; }
        public int CodCircuito { get; set; }
        public string NombreDespacho { get; set; }
        public int CantTecJud { get; set; }
        public int CantTecJur { get; set; }
        public int CantCoordJud { get; set; }
        public int CantJuezCoord { get; set; }
        public int CantJuezTram { get; set; }
        public int CantJueces { get; set; }
        public int CantOtros { get; set; }
    
        public virtual Circuito Circuito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Puesto_Despacho> Puesto_Despacho { get; set; }
    }
}
