//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos_Permitidos
    {
        public int IDPermitido { get; set; }
        public int TipoEquipo1 { get; set; }
        public int TipoEquipo2 { get; set; }
    
        public virtual TipoEquipo TipoEquipo { get; set; }
        public virtual TipoEquipo TipoEquipo3 { get; set; }
    }
}
