//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Equipo1 = new HashSet<Equipo>();
            this.Equipo2 = new HashSet<Equipo>();
        }
    
        public int Activo { get; set; }
        public string NumSerie { get; set; }
        public string Marca { get; set; }
        public string Descripcion { get; set; }
        public int TipoDeEquipo { get; set; }
        public int CodDespacho { get; set; }
        public string IDPuesto { get; set; }
        public int NumContrato { get; set; }
        public int IDEstado { get; set; }
        public bool Alquilado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Observaciones { get; set; }
        public string UsuarioCrea { get; set; }
        public string UsuarioModifica { get; set; }
        public System.DateTime UltimaModicacion { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Puesto_Despacho Puesto_Despacho { get; set; }
        public virtual TipoEquipo TipoEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo2 { get; set; }
    }
}
