//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJInventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PJInventarioEntities : DbContext
    {
        public PJInventarioEntities()
            : base("name=PJInventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Circuito> Circuito { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Despacho> Despacho { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Equipos_Permitidos> Equipos_Permitidos { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Historico> Historico { get; set; }
        public virtual DbSet<LogModificacion> LogModificacion { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Puesto_Despacho> Puesto_Despacho { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoEquipo> TipoEquipo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
