//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJInventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PJInventarioEntities : DbContext
    {
        public PJInventarioEntities()
            : base("name=PJInventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Circuito> Circuito { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Despacho> Despacho { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Equipos_Permitidos> Equipos_Permitidos { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Historico> Historico { get; set; }
        public virtual DbSet<LogModificacion> LogModificacion { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Puesto_Despacho> Puesto_Despacho { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoEquipo> TipoEquipo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int sp_Crea_Despacho(string pCodDespacho, Nullable<int> pCodCircuito, string pNombreDespacho, Nullable<int> pCantTecJud, Nullable<int> pCantTecJur, Nullable<int> pCantCoordJud, Nullable<int> pCantJuezCoord, Nullable<int> pCantJuezTram, Nullable<int> pCantJueces, Nullable<int> pCantOtros)
        {
            var pCodDespachoParameter = pCodDespacho != null ?
                new ObjectParameter("pCodDespacho", pCodDespacho) :
                new ObjectParameter("pCodDespacho", typeof(string));
    
            var pCodCircuitoParameter = pCodCircuito.HasValue ?
                new ObjectParameter("pCodCircuito", pCodCircuito) :
                new ObjectParameter("pCodCircuito", typeof(int));
    
            var pNombreDespachoParameter = pNombreDespacho != null ?
                new ObjectParameter("pNombreDespacho", pNombreDespacho) :
                new ObjectParameter("pNombreDespacho", typeof(string));
    
            var pCantTecJudParameter = pCantTecJud.HasValue ?
                new ObjectParameter("pCantTecJud", pCantTecJud) :
                new ObjectParameter("pCantTecJud", typeof(int));
    
            var pCantTecJurParameter = pCantTecJur.HasValue ?
                new ObjectParameter("pCantTecJur", pCantTecJur) :
                new ObjectParameter("pCantTecJur", typeof(int));
    
            var pCantCoordJudParameter = pCantCoordJud.HasValue ?
                new ObjectParameter("pCantCoordJud", pCantCoordJud) :
                new ObjectParameter("pCantCoordJud", typeof(int));
    
            var pCantJuezCoordParameter = pCantJuezCoord.HasValue ?
                new ObjectParameter("pCantJuezCoord", pCantJuezCoord) :
                new ObjectParameter("pCantJuezCoord", typeof(int));
    
            var pCantJuezTramParameter = pCantJuezTram.HasValue ?
                new ObjectParameter("pCantJuezTram", pCantJuezTram) :
                new ObjectParameter("pCantJuezTram", typeof(int));
    
            var pCantJuecesParameter = pCantJueces.HasValue ?
                new ObjectParameter("pCantJueces", pCantJueces) :
                new ObjectParameter("pCantJueces", typeof(int));
    
            var pCantOtrosParameter = pCantOtros.HasValue ?
                new ObjectParameter("pCantOtros", pCantOtros) :
                new ObjectParameter("pCantOtros", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Crea_Despacho", pCodDespachoParameter, pCodCircuitoParameter, pNombreDespachoParameter, pCantTecJudParameter, pCantTecJurParameter, pCantCoordJudParameter, pCantJuezCoordParameter, pCantJuezTramParameter, pCantJuecesParameter, pCantOtrosParameter);
        }
    
        public virtual int sp_Crea_TipoEquipo(string pTipoEquipoNombre)
        {
            var pTipoEquipoNombreParameter = pTipoEquipoNombre != null ?
                new ObjectParameter("pTipoEquipoNombre", pTipoEquipoNombre) :
                new ObjectParameter("pTipoEquipoNombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Crea_TipoEquipo", pTipoEquipoNombreParameter);
        }
    
        public virtual int sp_Edita_TipoEquipo(Nullable<int> iDTipoEquipo, string nombre)
        {
            var iDTipoEquipoParameter = iDTipoEquipo.HasValue ?
                new ObjectParameter("IDTipoEquipo", iDTipoEquipo) :
                new ObjectParameter("IDTipoEquipo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Edita_TipoEquipo", iDTipoEquipoParameter, nombreParameter);
        }
    
        public virtual int sp_Edita_Despacho(string pCodDespacho, Nullable<int> pCodCircuito, string pNombreDespacho, Nullable<int> pCantTecJud, Nullable<int> pCantTecJur, Nullable<int> pCantCoordJud, Nullable<int> pCantJuezCoord, Nullable<int> pCantJuezTram, Nullable<int> pCantJueces, Nullable<int> pCantOtros)
        {
            var pCodDespachoParameter = pCodDespacho != null ?
                new ObjectParameter("pCodDespacho", pCodDespacho) :
                new ObjectParameter("pCodDespacho", typeof(string));
    
            var pCodCircuitoParameter = pCodCircuito.HasValue ?
                new ObjectParameter("pCodCircuito", pCodCircuito) :
                new ObjectParameter("pCodCircuito", typeof(int));
    
            var pNombreDespachoParameter = pNombreDespacho != null ?
                new ObjectParameter("pNombreDespacho", pNombreDespacho) :
                new ObjectParameter("pNombreDespacho", typeof(string));
    
            var pCantTecJudParameter = pCantTecJud.HasValue ?
                new ObjectParameter("pCantTecJud", pCantTecJud) :
                new ObjectParameter("pCantTecJud", typeof(int));
    
            var pCantTecJurParameter = pCantTecJur.HasValue ?
                new ObjectParameter("pCantTecJur", pCantTecJur) :
                new ObjectParameter("pCantTecJur", typeof(int));
    
            var pCantCoordJudParameter = pCantCoordJud.HasValue ?
                new ObjectParameter("pCantCoordJud", pCantCoordJud) :
                new ObjectParameter("pCantCoordJud", typeof(int));
    
            var pCantJuezCoordParameter = pCantJuezCoord.HasValue ?
                new ObjectParameter("pCantJuezCoord", pCantJuezCoord) :
                new ObjectParameter("pCantJuezCoord", typeof(int));
    
            var pCantJuezTramParameter = pCantJuezTram.HasValue ?
                new ObjectParameter("pCantJuezTram", pCantJuezTram) :
                new ObjectParameter("pCantJuezTram", typeof(int));
    
            var pCantJuecesParameter = pCantJueces.HasValue ?
                new ObjectParameter("pCantJueces", pCantJueces) :
                new ObjectParameter("pCantJueces", typeof(int));
    
            var pCantOtrosParameter = pCantOtros.HasValue ?
                new ObjectParameter("pCantOtros", pCantOtros) :
                new ObjectParameter("pCantOtros", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Edita_Despacho", pCodDespachoParameter, pCodCircuitoParameter, pNombreDespachoParameter, pCantTecJudParameter, pCantTecJurParameter, pCantCoordJudParameter, pCantJuezCoordParameter, pCantJuezTramParameter, pCantJuecesParameter, pCantOtrosParameter);
        }
    }
}
